google.client.id=235100421101-31uq9hf5j5vgon3ugum57k51li5a1vdi.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost/google-login
google.api.key=AIzaSyBEVZw2dPY20CuY1Ip_w8D6y8zUMam7-jE