-- 1. 면접 일정 테이블 생성
CREATE TABLE SCHEDULE
(
    SCHEDULE_ID    NUMBER PRIMARY KEY,
    MEMBER_ID      NUMBER        NOT NULL,
    COMPANY_NAME   VARCHAR2(100) NOT NULL,
    SCHEDULE_DATE  DATE          NOT NULL,
    SCHEDULE_TIME  VARCHAR2(10),
    INTERVIEW_TYPE VARCHAR2(20),
    MEMO           VARCHAR2(500),
    CREATED_DATE   DATE,
    app_id  number,

    CONSTRAINT FK_SCHEDULE_MEMBER
        FOREIGN KEY (MEMBER_ID)
            REFERENCES MEMBER (MEMBER_ID),

    CONSTRAINT FK_APP_ID
        FOREIGN KEY (APP_ID)
            REFERENCES APPLICATION (APP_ID)
        ON DELETE CASCADE
);


SELECT *
FROM MEMBER;

-- 3. 일정 고유 ID(PK) 자동 증가를 위한 시퀀스 생성
CREATE SEQUENCE SEQ_SCHEDULE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

TRUNCATE TABLE SCHEDULE;

INSERT INTO SCHEDULE
VALUES (SEQ_SCHEDULE.nextval, 3, '네이버', TO_DATE('2026-04-05', 'YYYY-MM-DD'), '14:00', '기술면접', '코딩 테스트 이후 1차 면접',
        SYSDATE,1);
INSERT INTO SCHEDULE
VALUES (SEQ_SCHEDULE.nextval, 4, '카카오', TO_DATE('2026-04-10', 'YYYY-MM-DD'), '10:30', '인성면접', '비대면 화상 면접', SYSDATE,3);

SELECT *
FROM SCHEDULE;

rollback;

select * from COMPANY;

select * from APPLICATION;

-- 1. 나중에 구글 달력이랑 연결할 때 쓸 '이름표 자리(빈칸)' 하나 만들기
ALTER TABLE SCHEDULE
    ADD (GOOGLE_EVENT_ID VARCHAR2(255));

-- 2. 정보 찾는 속도를 엄청 빠르게 해주는 '책갈피(인덱스)' 3개 꽂아두기
CREATE INDEX IDX_SCHEDULE_MEMBER ON SCHEDULE (MEMBER_ID);
CREATE INDEX IDX_SCHEDULE_DATE ON SCHEDULE (SCHEDULE_DATE);
CREATE INDEX IDX_APPLICATION_MEMBER ON APPLICATION (MEMBER_ID);

UPDATE APPLICATION
SET interview_date = '2026-04-03',
    interview_time = '14:00',
    interview_type = '대면'
WHERE APP_ID = 8;

select *
from APPLICATION;

UPDATE APPLICATION
SET interview_date = '2026-04-03',
    interview_time = '14:00',
    interview_type = '대면'
WHERE APP_ID = 3;

SELECT s.SCHEDULE_ID, s.SCHEDULE_DATE, c.COMPANY_NAME, a.POSITION
FROM SCHEDULE s
         JOIN APPLICATION a ON s.APP_ID = a.APP_ID
         JOIN COMPANY c ON a.COMPANY_ID = c.COMPANY_ID
WHERE a.MEMBER_ID = 3;

ALTER TABLE SCHEDULE
    ADD APP_ID NUMBER;

ALTER TABLE SCHEDULE
    ADD CONSTRAINT FK_SCHEDULE_APPLICATION
        FOREIGN KEY (APP_ID)
            REFERENCES APPLICATION (APP_ID)
                ON DELETE CASCADE;

update SCHEDULE
set SCHEDULE.APP_ID = 1
where SCHEDULE_ID = 1;

update SCHEDULE
set SCHEDULE.APP_ID = 3
where SCHEDULE_ID = 2;

select *
from SCHEDULE;

drop table SCHEDULE;

select * from APPLICATION;

select * from MEMBER;

select * from COMPANY;

-- 1. 87번 지원서 (라인) 일정
INSERT INTO SCHEDULE (SCHEDULE_ID, MEMBER_ID, COMPANY_NAME, SCHEDULE_DATE, SCHEDULE_TIME, INTERVIEW_TYPE, MEMO, CREATED_DATE, APP_ID) VALUES (SEQ_SCHEDULE.nextval, 6, '라인', TO_DATE('2026-04-15', 'YYYY-MM-DD'), '14:00', '1차 면접', '코딩테스트 통과 후 첫 면접', SYSDATE, 87);

-- 2. 88번 지원서 (쿠팡) 일정
INSERT INTO SCHEDULE (SCHEDULE_ID, MEMBER_ID, COMPANY_NAME, SCHEDULE_DATE, SCHEDULE_TIME, INTERVIEW_TYPE, MEMO, CREATED_DATE, APP_ID) VALUES (SEQ_SCHEDULE.nextval, 6, '쿠팡', TO_DATE('2026-04-20', 'YYYY-MM-DD'), '10:30', '기술 면접', '라이브 코딩 및 CS 질문 대비', SYSDATE, 88);

-- 3. 89번 지원서 (우아한형제들) 일정
INSERT INTO SCHEDULE (SCHEDULE_ID, MEMBER_ID, COMPANY_NAME, SCHEDULE_DATE, SCHEDULE_TIME, INTERVIEW_TYPE, MEMO, CREATED_DATE, APP_ID) VALUES (SEQ_SCHEDULE.nextval, 6, '우아한형제들', TO_DATE('2026-04-25', 'YYYY-MM-DD'), '16:00', '최종 면접', '임원 면접 및 컬처핏 준비', SYSDATE, 89);

-- 이 쿼리를 돌렸을 때 지영님이 입력한 데이터가 짠! 하고 나와야 달력에 뜹니다.
SELECT s.SCHEDULE_ID, s.SCHEDULE_DATE, c.COMPANY_NAME, a.POSITION
FROM SCHEDULE s
         JOIN APPLICATION a ON s.APP_ID = a.APP_ID
         JOIN COMPANY c ON a.COMPANY_ID = c.COMPANY_ID
WHERE a.MEMBER_ID = 6; -- (여기도 본인이 세팅한 유저 번호 3 또는 6으로 확인)


update APPLICATION set MEMBER_ID = 6 where APP_ID in (87,88, 89);


