google.client.id=235100421101-teooogdc8mtjr2d5rksv7vb1anro6k9q.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost/google-login
google.api.key=AIzaSyD9-zbt9DIvVgUT58KC0PjR3F6tLzLGLF4